### PR TITLE
Enable the user to pick a color for hotspots that were already clicked

### PR DESCRIPTION
**Pull request by y0x**
The feature I´ve created is described here: https://github.com/h5p/h5p-image-hotspots/issues/9

### CODE REVIEW

**Comment by timothyylim** [comment]
Putting this through UX review before merging the code. You can follow the issue here:
https://h5ptechnology.atlassian.net/browse/HFP-236

**Comment by y0x** [comment]
@timothyylim  I´ve accidentally also pushed my second commit relating to: https://github.com/h5p/h5p-image-hotspots/issues/8 into this PR. :) Either you kick it out or leave it, the feature is also done and would have been my next PR.

Sorry, don´t use git so often ;)

**Comment by timothyylim** [comment]
Sure, I'm looking forward to seeing what you come up with!

**Comment by fnoks** [comment]
Thank you for your pull request - I think a lot of users will be happy with getting this new functionality in place :)

It would be great if you could split this into two pull requests (one for the colors, and one for the icons). My comments, for now, will be related to the original issue.

I think you have done a good job with this and only have a few comments:
1) Wouldn't it be better to change the foreground color on the icon instead of the background color? At least with the current icon, this looks/feels better.
2) It has already been mentioned in the JIRA issue if you can move the new settings out of the group, and make the secondary color widget only being shown when the checkbox is checked. I don't think you should use the conditional-widget for this, but rather the ShowWhen widget. This means you must add an editorDependency to library.json, and update semantics.json to use it like this example: https://github.com/h5p/h5p-editor-show-when#using-boolean-field-as-trigger.

**Pull request closed without merging**
